Repository forgecommunitywiki/Documentation, pull requests merged in 2021-05, with the labels that each got.

#30 Contributing Cleanup
  docs/forgedev/index.md
  docs/forgedev/prguidelines.md
Labels: 1.15, Formatting, Text Fixes, Upstream

#35 Removed extra 's'
  docs/datagen/intro.md
Labels: 1.15, Text Fixes, Upstream

#38 Clarify Ambiguity in GLM Json
  docs/items/globallootmodifiers.md
Labels: 1.15, Out of Date Information, Text Fixes, Upstream

#39 [1.15.x] Fix outdated references in SimpleImpl Documentation
  docs/networking/simpleimpl.md
Labels: 1.15, Text Fixes, Upstream

#36 Porting Update
  docs/legacy/index.md
  docs/legacy/porting.md
  mkdocs.yml
Labels: 1.16, Out of Date Information

#37 Migrate to Mojmap
  docs/advanced/accesstransformers.md
  docs/blocks/blocks.md
  docs/blocks/interaction.md
  docs/blocks/states.md
  docs/concepts/internationalization.md
  docs/concepts/lifecycle.md
  docs/concepts/registries.md
  docs/concepts/sides.md
  docs/datagen/intro.md
  docs/datastorage/capabilities.md
  docs/effects/particles.md
  docs/effects/sounds.md
  docs/gettingstarted/debugprofiler.md
  docs/gettingstarted/index.md
  docs/items/items.md
  docs/models/advanced/ibakedmodel.md
  docs/models/advanced/itemoverridelist.md
  docs/models/advanced/perspective.md
  docs/models/overrides.md
  docs/networking/entities.md
  docs/networking/simpleimpl.md
  docs/rendering/ister.md
  docs/tileentities/tileentity.md
  docs/utilities/tags.md
Labels: 1.16, Out of Date Information, Text Fixes
