Repository forgecommunitywiki/Documentation, pull requests merged in 2021-04, with the labels that each got.

#7 Add local copies of icons
  forge_theme/base.html
  forge_theme/images/android-chrome-192x192.png
  forge_theme/images/apple-touch-icon.png
  forge_theme/images/browserconfig.xml
  forge_theme/images/favicon-16x16.png
  forge_theme/images/favicon-32x32.png
  forge_theme/images/favicon.ico
  forge_theme/images/logo.svg
  forge_theme/images/manifest.json
  forge_theme/images/mstile-150x150.png
  forge_theme/images/mstile-310x150.png
  forge_theme/images/mstile-310x310.png
  forge_theme/images/mstile-70x70.png
  forge_theme/images/safari-pinned-tab.svg
Labels: 1.15, Upstream

#4 Update Contributing Setup Instructions for Eclipse
  docs/forgedev/index.md
Labels: 1.15, Text Fixes, Upstream

#5 Address #357
  docs/gettingstarted/index.md
Labels: 1.15, Text Fixes, Upstream

#6 Address #178
  docs/networking/simpleimpl.md
Labels: 1.15, Text Fixes, Upstream

#8 Address all Typos
  docs/animation/asm.md
  docs/blocks/blocks.md
  docs/concepts/internationalization.md
  docs/concepts/lifecycle.md
  docs/concepts/registries.md
  docs/concepts/resources.md
  docs/conventions/loadstages.md
  docs/events/intro.md
  docs/forgedev/index.md
  docs/gettingstarted/structuring.md
  docs/items/items.md
  docs/models/advanced/ibakedmodel.md
  docs/models/advanced/perspective.md
  docs/models/files.md
  docs/models/introduction.md
  docs/networking/entities.md
  docs/networking/simpleimpl.md
  docs/utilities/recipes.md
Labels: 1.15, Text Fixes, Upstream

#9 Update 'Getting Started' Subdirectory
  docs/gettingstarted/autoupdate.md
  docs/gettingstarted/debugprofiler.md
  docs/gettingstarted/index.md
  docs/gettingstarted/structuring.md
Labels: 1.15, Out of Date Information, Text Fixes, Upstream

#10 Concepts Cleanup
  docs/concepts/data.md
  docs/concepts/internationalization.md
  docs/concepts/lifecycle.md
  docs/concepts/registries.md
  docs/concepts/resources.md
  docs/concepts/sides.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#12 Tile Cleanup
  docs/tileentities/tesr.md
  docs/tileentities/tileentity.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#13 Items cleanup
  docs/items/globallootmodifiers.md
  docs/items/items.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#14 Rendering Cleanup
  docs/rendering/ister.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#15 Add GLMP to Data Providers
  docs/datagen/intro.md
Labels: 1.16, Out of Date Information

#11 Blocks Cleanup
  docs/blocks/blocks.md
  docs/blocks/interaction.md
  docs/blocks/states.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#16 Add GlobalLootModifierSerializer::write
  docs/items/globallootmodifiers.md
Labels: 1.16, Out of Date Information

#19 Effects Cleanup
  docs/effects/particles.md
  docs/effects/sounds.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#21 Hide Animation API
  mkdocs.yml
Labels: 1.15, Upstream

#23 Networking Cleanup
  docs/networking/entities.md
  docs/networking/index.md
  docs/networking/overview.md
  docs/networking/simpleimpl.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#17 Events Cleanup
  docs/events/intro.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#18 Utilities cleanup
  docs/utilities/recipes.md
  docs/utilities/tags.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#20 Data Storage Cleanup
  docs/datastorage/capabilities.md
Labels: 1.15, Out of Date Information, Text Fixes, Upstream

#24 Events Cleanup Update
  docs/events/intro.md
Labels: 1.16, Out of Date Information

#25 Utilities Cleanup Update
  docs/utilities/tags.md
Labels: 1.16, Out of Date Information

#26 Switch Cap Invalidation to `#invalidateCaps`
  docs/datastorage/capabilities.md
Labels: 1.16, Out of Date Information

#27 Address Unorder Lists Format Error
  docs/utilities/tags.md
Labels: 1.15, Formatting, Upstream

#22 Models Cleanup
  docs/models/advanced/ibakedmodel.md
  docs/models/advanced/itemoverridelist.md
  docs/models/color.md
  docs/models/files.md
  docs/models/introduction.md
  docs/models/overrides.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#28 Add Method and Void Descriptors
  docs/advanced/accesstransformers.md
Labels: 1.15, Out of Date Information, Text Fixes, Upstream

#29 Conventions Cleanup
  docs/conventions/loadstages.md
  docs/conventions/locations.md
  docs/conventions/versioning.md
Labels: 1.15, Formatting, Out of Date Information, Text Fixes, Upstream

#31 Porting Cleanup
  docs/legacy/index.md
  docs/legacy/porting.md
  docs/legacy/porting1415.md
  mkdocs.yml
Labels: 1.15, Formatting, Text Fixes, Upstream

#32 Models Cleanup Update
  docs/models/advanced/ibakedmodel.md
  docs/models/overrides.md
Labels: 1.16, Formatting, Out of Date Information, Text Fixes

#33 Loading Stages: DeferredWorkQueue -> enqueueWork
  docs/conventions/loadstages.md
Labels: 1.16, Out of Date Information
